#!/usr/bin/ruby

SRC_DIR = File.dirname(File.expand_path(__FILE__)).gsub(`echo ~`.chomp, '~')

cmd = "time cat #{SRC_DIR}/test2.fasta | \\\n" +
      "  #{SRC_DIR}/../fasta-to-html > \\\n" +
      "  test2.html"

puts cmd
exec cmd
