#!/usr/bin/ruby

##    clustalw-to-html - multiple sequence alignment visualization in HTML
##    Copyright (C) 2009  Aleksandr O. Levchuk
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.

ACCESSIONS = []
SEQUENCES  = []
HEADERS    = []

def read
  fist_line = STDIN.gets
  exit if fist_line.nil?

  HEADERS.push fist_line.chomp

  # Skip empty lines
  while c = STDIN.getc
    if c.chr != "\n"
      STDIN.ungetc(c)
      break
    end
  end

  seq_id = 0
  while line = STDIN.gets
    line.gsub!(/[:*.]/, '') # Remove consensus information

    line.strip!
    if line.empty?
      seq_id = 0
      next
    end

    s = line.split(" ")
    accession, partial_sequence = s

    ACCESSIONS[seq_id] ||= accession
    current = SEQUENCES[seq_id]
    SEQUENCES[seq_id] = (current || "") + partial_sequence

    seq_id += 1
  end
end

def output
  SEQUENCES.each_with_index do |seq, i|
    puts ">#{ACCESSIONS[i]}"
    puts seq.scan(/.{79}/)
  end
end

read
output

