#!/usr/bin/ruby

ACCESSIONS = []
SEQUENCES  = []
TEMPLATE   = []

HEADER     = STDIN.gets.chomp

def read
  # Skip empty lines
  while c = STDIN.getc
    if c.chr != "\n"
      STDIN.ungetc(c)
      break
    end
  end
  
  seq_id = 0
  while line = STDIN.gets
    line.strip!
    if line.empty?
      seq_id = 0
      next
    end
  
    s = line.split(" ")
    accession, partial_sequence = s
  
    ACCESSIONS[seq_id] ||= accession  
    current = SEQUENCES[seq_id]
    SEQUENCES[seq_id] = (current || "") + partial_sequence
  
    seq_id += 1
  end
end

def load_template
  File.open(__FILE__) do |f|
    while line = f.gets
      break if line =~ /^# *%%TEMPLATE%%/
    end
    while line = f.gets
      line.strip!
      break if !(line =~ /^##/) # all lines in must start with ##
      TEMPLATE.push(line.sub(/## ?/, '') + "\n")
    end
  end
end

def generate
  longest = ACCESSIONS.inject(0){|result, element| [result, element.size].max}
  TEMPLATE.each do |line|
    line.gsub!('%%HEADER%%', HEADER)
    if line =~ /%%SEQUENCE%%/
      SEQUENCES.each_with_index do |s, i| 
        puts line.sub('%%SEQUENCE%%', "#{ACCESSIONS[i].ljust(longest)} #{s}")
      end
    else
      puts line
    end
  end
end



read
load_template
generate



# %%TEMPLATE%%
## <?xml version="1.0" encoding="utf-8"?>
## <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
## 
## <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
## <head>
## <title>clustalw-to-html</title>
## 
## </head>
## <body>
## 
## <h1>%%HEADER%%</h1>
## 
## <div style="white-space: pre; font-family: monospace; ">%%SEQUENCE%%</div>
## 
## 
## <p style="margin-top: 5em;">
## 
##   <a href="http://validator.w3.org/check?uri=referer&amp;ss=checked&amp;outline=checked"><img
##     style="border: 0px"
##     src="http://www.w3.org/Icons/valid-xhtml10"
##     alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a>
## 
##  <a href="http://jigsaw.w3.org/css-validator/check/referer">
##   <img style="border:0;width:88px;height:31px"
##        src="http://jigsaw.w3.org/css-validator/images/vcss" 
##        alt="Valid CSS!" />
##  </a>
## </p>
## 
## </body>
## </html>
