#!/bin/sh

set -e

SRC_DIR=`dirname $0`
PLUGINS=$SRC_DIR/plugins/*.savvy

# Keep only the executable Plugins
PLUGINS=`for i in $PLUGINS; do if [ -x $i ]; then echo $i; fi; done`

PLUGIN_NAMES=`for i in $PLUGINS; do basename $i; done; echo`


IMPORT=$SRC_DIR/savvy-import-fasta
GENERATE=$SRC_DIR/savvy-generate-html

if [ $# != 1 ]; then
  echo "Usage: `basename $0` <fasta_file> [plugin options] [display options]"
  exit 1
fi

FASTA=$1

# TODO: Parse Plugin and Display options
PLUGIN_OPTIONS=""
DISPLAY_OPTIONS=""


# Run savvy-import-fasta
$IMPORT $FASTA ${FASTA}_msa.json ${FASTA}_headers.json


# Run savvy-generate-html
all_plugins=`for i in $PLUGIN_NAMES; do echo -n "-p $i "; done; echo`
$GENERATE $FASTA $all_pligins ${FASTA}_savvy.html $all_plugins


# Run all Plugins
for plugin in $PLUGINS; do
  p_name=`basename $plugin`
  $plugin ${FASTA}_msa.json > ${FASTA}_${p_name}.json
done


# Cleanup
#*_headers.json
#*_msa.json
