#!/usr/bin/env Rscript

library(rjson)
library(multicore)

initial.options <- commandArgs()
file.arg.name <- "--file="

script.path <- sub(file.arg.name, "", 
  initial.options[grep(file.arg.name, initial.options)])

script.path.list <- strsplit(script.path, '/')[[1]]
script.dir.list  <- script.path.list[1:(length(script.path.list)-1)]

software.dir  <- paste(c(script.dir.list, '..'), sep='/', collapse='/')
script.name <- script.path.list[[length(script.path.list)]]



script.args <- commandArgs(trailingOnly=T)

if(length(script.args) != 1) {
       cat(paste(
         paste("Usage:", script.name, "<webdata>\n"),
         "Required Options",
         "  <webdata>      directory with files produced by the analyzer",
         "",
         sep="\n"))
       quit()
}

dir.path.webdata  <- sub("/$", "", script.args[[1]])
dir.plugins  <- paste(software.dir, "plugins", sep='/')

file.menu    <- paste(dir.path.webdata, 'menu.json', sep='/')

# Read the Menu file
menu    <- fromJSON(readLines(file.menu))

# TODO: More checks (dirs exists, at least 1 plugin exist)

run.plugin <- function (name.plugin) {
   out <-
     pipe(paste(
       paste(dir.plugins, name.plugin, sep="/"),
       paste(dir.path.webdata, "msa.json", sep="/"),
       sep=" ")
     )

   writeLines(readLines(out),
     paste(dir.path.webdata, paste(name.plugin, ".json", sep=''), sep="/"))
}

# Run plugins in parralel
jobs <- lapply(menu$plugins, function(x) parallel(run.plugin(x), name=x))
invisible(collect(jobs))
