#!/usr/bin/env Rscript

library(seqinr) # for read.fasta


importFasta <- function() {
        fasta <- read.fasta(file.fasta, seqtype = "AA")
        seqs_info <- data.frame(id=1:length(fasta), headers=names(fasta))
        msa <- sapply(fasta, function(i){as.character(i)})
        return(list(seqs_info=seqs_info, msa=msa))
}

make_html_seqs <- function(seqs_info, msa){
       html_msa <- apply(msa, 1, function(r){paste("<b>", r, "</b>", sep="")})
       html_msa <- t(html_msa) # Transpose!
       lines    <- apply(html_msa, 2, function(i){paste(i, collapse="")})
       o        <- paste("<div class=\"s\" id=\"seq", seqs_info$id, "\">",
                         lines, "</div>", sep="")
       return(o)
}

applyTemplate <- function(html_seqs, title=title, json=json) {
        lines <- readLines(
          paste(script.dir, "/savvy.template.html", sep=""))

        lines <- lapply(lines, function(l){sub("%%SEQUENCES%%", html_seqs, l)})
        lines <- lapply(lines, function(l){sub("%%TITLE%%", title, l)})
        lines <- lapply(lines, function(l){sub("%%JSON_FILE%%", json, l)})
        lines <- lapply(lines, function(l){sub("%%GEN_DATE%%", Sys.time(), l)})

        lines <- paste(lines, sep = "", collapse="\n")
        return(lines)
}



initial.options <- commandArgs()
file.arg.name <- "--file="

script.path <- sub(file.arg.name, "", 
  initial.options[grep(file.arg.name, initial.options)])

script.path.list <- strsplit(script.path, '/')[[1]]
script.dir.list  <- script.path.list[1:(length(script.path.list)-1)]

script.dir  <- paste(script.dir.list, sep='/', collapse='/')
script.name <- script.path.list[[length(script.path.list)]]



script.args <- commandArgs(trailingOnly=T)

if(length(script.args) != 2) {
       cat(paste("Usage:", script.name, "<file.fasta> <file.json>", "\n\n"))
       cat(paste("Required Options", "\n\n"))
       cat(paste(
         "  <file.fasta> is the multiple sequence alignment (msa)", "\n"))
       cat(paste(
         "  <file.json>  describes colors and positions for highlighting",
         "\n"))
       quit()
}

file.fasta <- script.args[[1]]
file.json  <- script.args[[2]]




fasta <- importFasta()

html_seqs  <- make_html_seqs(fasta$seqs_info, fasta$msa)
html_chunk <- paste(html_seqs, sep = "", collapse="\n")


j_list <- strsplit(file.json, '/')[[1]]
j      <- j_list[[length(j_list)]]
cat(applyTemplate(html_chunk, title=file.fasta, json=j), "\n")

